### PR TITLE
refactor: improved error contexts

### PR DESCRIPTION
**Pull request by JanMalch**
- improved error contexts
- removed unused error

### CODE REVIEW

**Comment by splincode** [comment]
@JanMalch Could you write tests for each feature?

**Comment by JanMalch** [comment]
@splincode Which features do you mean?

**Comment by splincode** [comment]
@JanMalch any, because CI is necessary so that before merge we understand that it has fallen or not

**Comment by JanMalch** [comment]
I already have a lot of tests. The project structure will be refactored soon. I will run coverage afterwards, but it should be pretty high already.

**Pull request merged**
